#!/usr/bin/python
import fileinput
import os
import sys

from ConfigParser import SafeConfigParser


class FakeSecHead(object):
    def __init__(self, fp):
        self.fp = fp
        self.sechead = '[FAKESECTION]\n'

    def readline(self):
        if self.sechead:
            try:
                return self.sechead
            finally:
                self.sechead = None
        else:
            return self.fp.readline()

if __name__ == "__main__":
    config = SafeConfigParser(os.environ)
    config.readfp(FakeSecHead(fileinput.input()))
    config._defaults = None
    config.write(sys.stdout)
