#!/usr/bin/env python
import json
import os
import sys

import onepasswordconnectsdk as OP
from onepasswordconnectsdk.client import (
    Client,
    new_client_from_environment
)


def out(msg, code=1):
    sys.stdout.write(msg)
    exit(0)


def err(msg, code=1):
    sys.stderr.write(msg + '\n')
    exit(code)


if __name__ == "__main__":
    cred_schema = json.loads(sys.stdin.readline())
    if (len(cred_schema) > 1):
        err("Only a single credential specification supported. {} provided.".format(list(cred_schema)))
    key_field = list(cred_schema)[0]
    creds_client: Client = new_client_from_environment(url=os.environ['OP_CONNECT_SERVER'])
    creds = OP.load_dict(client=creds_client, config=cred_schema)
    if key_field not in creds:
        err("Expected [{}] field in server response.".format(key_field))
    out(creds[key_field])