#!/usr/bin/env python
import json
import os
import sys

import onepasswordconnectsdk as OP
from onepasswordconnectsdk.client import (
    Client,
    new_client_from_environment
)


def out(msg, code=1):
    sys.stdout.write(msg)
    exit(0)


def err(msg, code=1):
    sys.stderr.write(msg + '\n')
    exit(code)


if __name__ == "__main__":
    cred_schema = json.loads(sys.stdin.readline())
    if (len(cred_schema) > 1):
        err("Only single credential supported.")
    creds_client: Client = new_client_from_environment(url=os.environ['OP_CONNECT_SERVER'])
    creds = OP.load_dict(client=creds_client, config=cred_schema)
    if 'fields' not in creds or len(creds['fields'] != 1):
        err("Invalid response from creds server.")
    out(creds['fields'][0]['value'])