#!/bin/bash
filename=$1
shift
words=$*
if [ -z "$filename" ]; then
  echo "You need to specify a filename to save."
  exit 1
fi
if [ -z "$words" ]; then
  echo "You need to specify a sentence to save to $filename"
  exit 2
fi
if [ -f "$filename" ]; then
  echo "$filename already exists for sentence $words"
  exit 3
fi
wget -q -U Mozilla -O $filename "http://translate.google.com/translate_tts?tl=en&q=$*"
