#!/usr/bin/python
import os
from time import time

from resin.auth import Auth
from resin.models.application import Application
from resin.models.device import Device
from resin.models.environment_variables import ApplicationEnvVariable

if __name__ == "__main__":
    #for k,v in os.environ.items():
    #    print '{}: {}'.format(k,v)

    resin_auth = Auth()
    resin_auth.login_with_token(os.environ.get('AUTH_KEY_RESIN'))
    device_id = os.environ.get('RESIN_DEVICE_UUID')
    device = Device()
    device_app_name = device.get_application_name(device_id)
    device_name = device.get_name(device_id)
    device_ip = device.get_local_ip_address(device_id)
    print 'Device {} ({}) is running app {}'.format(device_name, device_ip, device_app_name)
    application = Application()
    print 'I am running application {}'.format(str(application.get(device_app_name)))
    #{u'app_name': u'SnapshotProcessor', u'__metadata':
    # {u'type': u'', u'uri': u'/ewa/application(5231)'}, u'git_repository': u'tglucas@git.resin.io:tglucas/snapshotprocessor.git',
    # u'user': {u'__deferred': {u'uri': u'/ewa/user(4554)'}, u'__id': 4554}, u'device_type': u'raspberry-pi', u'commit': u'418e2d97a03300274a9c42ffc340cf0a18497020', u'id': 5231}
    environment_variables = ApplicationEnvVariable()
    test_data = '{}'.format(time())
    environment_variables.update('DYNAMIC_TEST', test_data)
