region: eu
log_level: info
log_format: json
log: false
web_addr: 0.0.0.0:4040
tunnels:
  frontend:
    proto: http
    bind_tls: true
    addr: APP_FLASK_HTTP_PORT
    auth: "FRONTEND_USER:FRONTEND_PASSWORD"
